#!/usr/bin/env groovy
/**
 * The purpose of this script is to enable the scheduled run of automated test cases. <br/>
 *
 */

// Import BMW specific libraries
// @Library("atc-jenkins-shared-library")
// import com.bmw.atc.jenkins.steps.*
import groovy.transform.Field

// def pipelineSteps = new PipelineSteps(this)
// def scmSteps = new SCMSteps(this)
// def emailSteps = new EmailSteps(this)
// def projectName = pipelineSteps.multiBranchDisplayName()
def jiraUrl = "https://test4xray.atlassian.net"
def apiVersion = "3"
def xrayUrl = "https://xray.cloud.xpand-it.com"
def itTest = 10005
def itTestSet = 10006
def testSetStat = "In+Progress"
def testSetLbl = "Robot"
def itTestExc = 10008
def itTestPlan = 10007
def testPlanStat = "In+Progress"
def testPlanLbl = "Robot"
def testTypes = ["REST_API", "WebUI"]
def jiraSystemKeys = ["TA2MBT"]
def jiraProjectKeys = ["TA2MBT": "TA2"]
def jiraProjectKey = "" // will be set later
def testPrefixes = ["TA2MBT": "TA2"]
final def searchLabel = "Robot"

// set reference to a separate variable to allow access to pipeline steps container from within closure execution
def me = this

/**
 * Credentials
 */
final def JiraCredentials = "XRAY"


def parameterList = []

node('master') {
    withCredentials([usernamePassword(credentialsId: JiraCredentials, usernameVariable: 'JIRA_USER', passwordVariable: 'JIRA_PASSWORD')]) {
        def testPlans = ['all']
        def testSets = ['all']
        def projects = jiraProjectKeys.values().unique()
        projects.each({project ->
            // Get the actual Test Plan to assign Test Executions to
            curlCmd = "curl -u \${JIRA_USER}:\${JIRA_PASSWORD} -X GET -H 'Content-Type: application/json' '${jiraUrl}/rest/api/${apiVersion}/search?jql=project%3D%22${project}%22+AND+issuetype%3D%22${itTestPlan}%22+AND+status+in+(%22${testPlanStat}%22)+AND+labels+in+(%22${testPlanLbl}%22)&fields=key'"
            println "Command executed: ${curlCmd}"
            def curlResult = sh(returnStdout: true, script: curlCmd).trim()
            def jsonSlurper = new groovy.json.JsonSlurper()
            def curlResultObject = jsonSlurper.parseText("" + curlResult)
            def testPlanList = curlResultObject.issues.collect { it.key }
            testPlans.addAll(testPlanList)
            println "Test Plan is ${testPlans}"
        })
        def projects2 = jiraProjectKeys.values().unique()
        projects2.each({project ->
            // Get all test sets out of Jira/XRay that has a specific label and are ready for execution
            curlCmd2 = "curl -u \${JIRA_USER}:\${JIRA_PASSWORD} -X GET -H 'Content-Type: application/json' '${jiraUrl}/rest/api/${apiVersion}/search?jql=project%3D%22${project}%22+and+type%3D%22${itTestSet}%22+and+labels+in+(%22${testSetLbl}%22)+AND+status+in+(%22${testSetStat}%22)&fields=key,summary'"
            println "Command executed: ${curlCmd2}"
            def curlResult2 = sh(returnStdout: true, script: curlCmd2).trim()
            def jsonSlurper2 = new groovy.json.JsonSlurper()
            def curlResultObject2 = jsonSlurper2.parseText("" + curlResult2)
            def testSetList = curlResultObject2.issues.collect { it.key + ": " + it.fields.summary }
            testSets.addAll(testSetList)
            println "Test Sets are ${testSets}"
        })

    parameterList.push(
        booleanParam(name: 'READ_CONFIG_ONLY', defaultValue: false, description: "If checked, the pipeline will be skipped and only the param config is recreated. The service fields and test sets are recreated with current values.")
    )
    parameterList.push(
        booleanParam(name: 'SEND_EMAIL', defaultValue: false, description: "Should an e-mail be sent to specific users?")
    )
    parameterList.push(
        booleanParam(name: 'UPDATE_XRAY', defaultValue: false, description: "Should the test results imported into a test execution and the test plan updated?")
    )
    parameterList.push(
        choice(name: 'TEST_PLAN', choices: testPlans, description: "Test Plan from XRay.")
    )
    parameterList.push(
        choice(name: 'TEST_TYPE', choices: testTypes, description: "What kind of tests should be executed via Robot Framework?")
    )
    parameterList.push(
        choice(name: 'TEST_SET', choices: testSets, description: "Test Set from XRay. If not all test sets are shown, please run the pipeline once with READ_CONFIG checked.")
    )
    }
}
properties ([
  parameters(
        parameterList
  )
])

// pipeline state variables
def abortedPipeline = false
def testIds = ''
def enableSendMail = false
def enableUpdateXray = false
def resultDir = ""
def testdefDir = ""

pipeline {
agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '20', daysToKeepStr: '7'))
        timeout(time: 100, unit: 'MINUTES')
        disableConcurrentBuilds()
        // timestamps ()
    }
    environment {
        ACCESS_KEY = credentials("${JiraCredentials}")
    }
	stages {
		stage ("Test Setup"){
            when {
                expression {
                    !abortedPipeline
                }
            }
            steps {
                script {
                    if (params.READ_CONFIG_ONLY) {
                        echo "Skipping pipeline and just getting information from Jira/XRay"
                        abortedPipeline = true
                        // further commands
                    } else {
                        echo "Preparing the test execution!"
                        enableSendMail = params.SEND_EMAIL
                        enableUpdateXray = params.UPDATE_XRAY
                        def testSummary = ""
                        // TODO: eventuell 'all' rausnehmen
                        if (params.TEST_SET != 'all') {
                            withCredentials([usernamePassword(credentialsId: JiraCredentials, usernameVariable: 'JIRA_USER', passwordVariable: 'JIRA_PASSWORD')]) {
                                def testSetKey = params.TEST_SET.split(":")[0]
                                println "Test Set Key = ${testSetKey}"
                                // jiraProjectKey = testSetKey.split("-")[0]
                                // def curlCmd = "curl -u ${me.env.ACCESS_KEY} '${jiraUrl}/rest/api/3/issue/${testSetKey}'"
                                // echo curlCmd
                                // def curlResult = sh(returnStdout: true, script: curlCmd).trim()
                                // echo curlResult
                                // def jsonSlurper = new groovy.json.JsonSlurper()
                                // def curlResultObject = jsonSlurper.parseText(""+curlResult)
                                // testIds = '' + (curlResultObject.findAll { it.type == 'Generic' }.collect { it.key }.join(" "))
                                // if (testIds == '') {
                                //    error "Test set ${params.TEST_SET} does not contain automated tests"
                                // }
                                def testSetString = '' + (params.TEST_SET).replace(": ",":  ")
                                println "Run Test Set ${testSetString}"
                                // println "Set contains test id(s) ${testIds}"
                            }
                        } else {
                            println "Running all tests"
                            abortedPipeline = true
                        }
                    }
                }
            }
		}
		stage ("Run Test Cases") {
            when {
                expression {
                    !abortedPipeline
                }
            }
            steps {
                script {
                    echo "Run Robot Framework test cases"
                    def testTypeKey = params.TEST_TYPE
                    def tagName = params.TEST_SET.split(":")[1]
                    resultDir = "results/${testTypeKey}/${BUILD_TAG}"
                    testdefDir = "testdefinition/${testTypeKey}"
                    sh "chmod 755 scripts/run_RF_Test_Cases.sh"
                    sh "./scripts/run_RF_Test_Cases.sh ${resultDir} ${testdefDir} ${tagName}"
                }
            }
		}
		stage ("Update Xray") {
            when {
                expression {
                    !abortedPipeline
                }
            }
            steps {
                script {
                    echo 'Importing test results into test execution'
                    // def testExecutionParam = ""
                    // def testProject = jiraSystemKeys.get(0)
                    //def testProjectParam = "projectKey=${testProject}"
                    // echo "Project name is ${testProjectParam}"
                    // Current directory
                    // def workspace = pwd()
                    // echo ${workspace}
                    // Getting a token from Jira
                    // def tokenCurl = "curl -H 'Content-Type: application/json' -X POST --data @'${authDir}/cloud_auth.json' '${$jiraUrl}/api/v2/authenticate'"
                    // def token = sh(returnStdout: true, script: tokenCurl).trim()
                    // def curlCmd = "curl -H 'Content-Type: application/xml' -X POST -H 'Authorization: Bearer ${token}' --data @'${resultDir}/output.xml' '${$jiraUrl}/api/v2/import/execution/robot?projectKey=$PROJECT&testPlanKey=$TESTPLAN&testEnvironment=$BROWSER'"
                    // def curlResult = sh(returnStdout: true, script: curlCmd).trim()
                    // echo "Command is ${curlCmd}"
                }
            }
		}
	}
	post {
	    always {
            echo 'I will always say Hello again!'
	    }
	    aborted {
            echo 'Pipeline aborted'
	    }
	    failure {
            echo 'Pipeline failure'
	    }
	    cleanup {
            echo 'Pipeline cleanup'
	    }
	    success {
            echo 'Pipeline success'
	    }
	}
}